### ISSUE TITLE
gcsfuse: command not found

### ISSUE THREAD

**Issue by case3526** [googlegenomics/gcp-deepvariant-runner#27]
# Model for calling whole genome sequencing data.
MODEL=gs://deepvariant/models/DeepVariant/0.8.0/DeepVariant-inception_v3-0.8.0+data-wgs_standard
IMAGE_VERSION=0.8.0
DOCKER_IMAGE=gcr.io/deepvariant-docker/deepvariant:"${IMAGE_VERSION}"
COMMAND="/opt/deepvariant_runner/bin/gcp_deepvariant_runner \
  --project ${PROJECT_ID} \
  --zones us-west1-* \
  --docker_image ${DOCKER_IMAGE} \
  --outfile ${OUTPUT_BUCKET}/${OUTPUT_FILE_NAME} \
  --gvcf_outfile ${OUTPUT_BUCKET}/${OUTPUT_gVCF_FILE_NAME} \
  --staging ${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME} \
  --model ${MODEL} \
  --bam gs://files_jays/bam/bqsr.realign.markdup.sorted.merged.bam \
  --bai gs://files_jays/bam/bqsr.realign.markdup.sorted.merged.bai \
  --ref gs://genomics-public-data/references/GRCh38_Verily/GRCh38_Verily_v1.genome.fa \
  --shards 512 \
  --make_examples_workers 32 \
  --make_examples_cores_per_worker 16 \
  --make_examples_ram_per_worker_gb 60 \
  --make_examples_disk_per_worker_gb 200 \
  --call_variants_workers 32 \
  --call_variants_cores_per_worker 32 \
  --call_variants_ram_per_worker_gb 60 \
  --call_variants_disk_per_worker_gb 50 \
  --preemptible \
  --max_preemptible_tries 5 \
  --gcsfuse"
# Run the pipeline.
gcloud alpha genomics pipelines run \
    --project "${PROJECT_ID}" \
    --service-account-scopes="https://www.googleapis.com/auth/cloud-platform" \
    --logging "${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME}/runner_logs_$(date +%Y%m%d_%H%M%S).log" \
    --regions us-west1 \
    --docker-image gcr.io/cloud-genomics-pipelines/gcp-deepvariant-runner \
    --command-line "${COMMAND}"

# logs on one of the VMs
/bin/bash: gcsfuse: command not found
parallel: This job failed:
mkdir -p ./input-gcsfused-0 && gcsfuse --implicit-dirs files_jays /input-gcsfused-0
/bin/bash: gcsfuse: command not found
parallel: This job failed:
mkdir -p ./input-gcsfused-1 && gcsfuse --implicit-dirs files_jays /input-gcsfused-1
/bin/bash: gcsfuse: command not found

**Comment by HagenC** [comment]
Just a guess- but add a white-space after --gcsfuse and " so i becomes --gcsfuse  ", not --gcfuse".

**Comment by samanvp** [comment]
This is known issue, we will be releasing a new docker image later this week that will resolve it.

**Comment by case3526** [comment]
Thanks @samanvp!

**Comment by samanvp** [comment]
We just released a new docker image located at `gcr.io/cloud-lifesciences/gcp-deepvariant-runner`. Please let us know if you still observe gcsfuse issue using the latest release.
